Default: &defaults
  host: "*4" # any IPv4 host
  port: 5000
  approot: "http://circusescape.com"
  copyright: Erlend Hamberg Â© 2013
  #analytics: UA-YOURCODE

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  #approot: "http://www.example.com"
  <<: *defaults
